/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    checkstyle
    pmd
    java
    kotlin("jvm") version "1.3.40"
    // Apply the application plugin to add support for building a CLI application
    application
    id("com.github.spotbugs") version "4.5.0"
}

buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.5.0")
  }
}

apply(plugin = "com.github.spotbugs")

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()

    flatDir {
        dirs("lib")
    }
}

spotbugs {
    showProgress.set(true)
    includeFilter.set(file("config/spotbugs/spotbugs.xml"))
    tasks.spotbugsMain {
        reports.create("html") {
            isEnabled = true
        }
    }
}

checkstyle {
    toolVersion = "8.15"
    configFile = file("config/checkstyle/checkstyle-coursera.xml")
    isIgnoreFailures = true
}

pmd {
    isConsoleOutput = false
    toolVersion = "6.27.0"
    rulePriority = 5
    ruleSetFiles = files("config/pmd/pmd.xml")
    reportsDir = file("build/reports/pmd")
    maxFailures.set(20)
}

dependencies {
    // This dependency is used by the application.
    implementation(kotlin("stdlib-jdk8"))
    // implementation("com.google.guava:guava:27.1-jre")
    //implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    implementation("edu.princeton.cs:algs4:1.0.4")
    implementation("com.thomasjensen.checkstyle.addons:checkstyle-addons:6.0.0")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application
    mainClassName = "BoardTest"
}
